# Generated by Django 5.0 on 2023-12-31 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('respiratory_disease', models.BooleanField(default=False)),
                ('cardiovascular_disease', models.BooleanField(default=False)),
                ('hepatobiliary_disease', models.BooleanField(default=False)),
                ('viral_hepatitis_disease', models.BooleanField(default=False)),
                ('nurological_disease', models.BooleanField(default=False)),
                ('tb_disease', models.BooleanField(default=False)),
                ('diabetes_disease', models.BooleanField(default=False)),
                ('rheumatic_fever_disease', models.BooleanField(default=False)),
                ('drug_allergy_disease', models.BooleanField(default=False)),
                ('pregnancy_disease', models.BooleanField(default=False)),
                ('blood_disease', models.BooleanField(default=False)),
                ('surgical_history_disease', models.BooleanField(default=False)),
                ('drug_history_disease', models.BooleanField(default=False)),
                ('allergic_history_disease', models.BooleanField(default=False)),
                ('endodontic_examination', models.CharField(blank=True, max_length=100, null=True)),
                ('tooth_number', models.CharField(blank=True, max_length=30, null=True)),
                ('type_of_affection', models.CharField(blank=True, max_length=100, null=True)),
                ('presence_of_pain', models.CharField(blank=True, max_length=30, null=True)),
                ('measure_of_pain', models.CharField(blank=True, max_length=30, null=True)),
                ('time_posture_of_pain', models.CharField(blank=True, max_length=30, null=True)),
                ('duration_of_pain', models.CharField(blank=True, max_length=30, null=True)),
                ('pain_initiated_by', models.CharField(blank=True, max_length=30, null=True)),
                ('pain_relieved_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='patient_appointment.appointment')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='patient_appointment.patient')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100, unique=True)),
                ('preparation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manufacturer', models.CharField(max_length=100)),
                ('medicine_description', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='prescription_app.history')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_interval', models.PositiveIntegerField()),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage_qty', models.PositiveIntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription_app.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_medicines', to='prescription_app.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_type', models.IntegerField(choices=[(1, 'Test Result is numerical'), (2, 'Test Result is categorical'), (3, 'Test Result contains attachment')])),
                ('created_at', models.DateField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='recommended_tests',
            field=models.ManyToManyField(to='prescription_app.test'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, choices=[('pH', 'pH'), ('mg/dL', 'mg/dL'), ('units/L', 'units/L'), ('mEq/dL', 'mEq/dL'), ('%', '%'), ('cells/μL', 'cells/μL'), ('μg/L', 'μg/L')], max_length=10, null=True)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='test_results/')),
                ('diagnostic_center', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='prescription_app.prescription')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription_app.test')),
            ],
            options={
                'verbose_name': 'Test Result',
                'verbose_name_plural': 'Test Results',
            },
        ),
    ]
