# Generated by Django 5.0 on 2023-12-31 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_appointment', '0001_initial'),
        ('prescription_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient_appointment.appointment'),
        ),
    ]
